# Generated by Django 4.1.5 on 2023-01-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0005_alter_project_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('text', models.TextField(max_length=10000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('text', models.TextField(max_length=10000)),
                ('confirmed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_project', to='project.project')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_team', to='project.team')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_project', to='project.project')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_team', to='project.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompletedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('text', models.TextField(max_length=10000)),
                ('checked', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ManyToManyField(related_name='task', to='message.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
