# Generated by Django 4.1.5 on 2023-01-08 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassignment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassignment',
            name='from_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_project', to='project.project'),
        ),
        migrations.AddField(
            model_name='reassignment',
            name='from_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_team', to='project.team'),
        ),
        migrations.AddField(
            model_name='reassignment',
            name='to_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_project', to='project.project'),
        ),
        migrations.AddField(
            model_name='reassignment',
            name='to_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_team', to='project.team'),
        ),
        migrations.AddField(
            model_name='completedtasks',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedtasks',
            name='task',
            field=models.ManyToManyField(related_name='task', to='message.task'),
        ),
    ]
