# Generated by Django 4.1.5 on 2023-01-08 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_alter_project_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('organization_name', models.CharField(max_length=200, unique=True)),
                ('members', models.ManyToManyField(related_name='org_members', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='org_owners', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='org_projects', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
