# Generated by Django 4.1.5 on 2023-01-08 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_team_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='org_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='org_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='org_projects', to='project.project'),
        ),
    ]
