# Generated by Django 4.1.5 on 2023-01-08 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0003_alter_organization_members_alter_organization_owners_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='owners',
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
