# Generated by Django 4.1.5 on 2023-01-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('message', '0003_rename_task_completedtasks_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
