# Generated by Django 4.1.5 on 2023-01-19 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0005_alter_organization_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0004_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('text', models.TextField(max_length=10000)),
                ('status', models.CharField(
                    choices=[('Confirmed', 'Confirmed'),
                             ('Waiting', 'Waiting'), ('Rejected', 'Rejected')],
                    default='Waiting', max_length=200)),
                ('creator',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
                ('to_organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
