# Generated by Django 4.1.5 on 2023-01-19 22:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0005_alter_organization_owner'),
        ('message', '0005_invite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invite',
            new_name='InviteToOrganization',
        ),
    ]
