# Generated by Django 4.1.5 on 2023-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('message', '0006_rename_invite_invitetoorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtasks',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='invitetoorganization',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='reassignment',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
