# Generated by Django 4.1.5 on 2023-01-23 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('message',
         '0007_completedtasks_active_invitetoorganization_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtasks',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='invitetoorganization',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='reassignment',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='active',
            new_name='is_active',
        ),
    ]
