# Generated by Django 4.1.5 on 2023-01-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0005_alter_organization_owner'),
        ('message', '0008_rename_active_completedtasks_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtasks',
            name='organization',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.organization'),
        ),
        migrations.AddField(
            model_name='reassignment',
            name='organization',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.organization'),
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.organization'),
        ),
    ]
