# Generated by Django 4.1.5 on 2023-01-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('Junior', 'Junior'), ('Junior Plus', 'Junior Plus'), ('Middle', 'Middle'), ('Middle Plus', 'Middle Plus'), ('Senior', 'Senior')], default='Junior', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperOrganizationSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full-Stack', 'Full-Stack'), ('Development & Operations', 'Development & Operations')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=200, unique=True)),
                ('technology_category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Development & Operations', 'Development & Operations'), ('General technologies', 'General technologies')], max_length=200)),
            ],
        ),
    ]
