# Generated by Django 4.1.5 on 2023-01-08 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('user', '0001_initial'),
        ('organization', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager_team', to='project.team'),
        ),
        migrations.AddField(
            model_name='developerorganizationspecialty',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='developerorganizationspecialty',
            name='organization_developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.developer'),
        ),
        migrations.AddField(
            model_name='developer',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AddField(
            model_name='developer',
            name='specialty',
            field=models.ManyToManyField(to='employee.developerorganizationspecialty'),
        ),
        migrations.AddField(
            model_name='developer',
            name='stack',
            field=models.ManyToManyField(blank=True, to='employee.technologies'),
        ),
        migrations.AddField(
            model_name='developer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_team', to='project.team'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
