# Generated by Django 4.1.5 on 2023-01-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_about_user'),
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', unique=True),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', unique=True),
        ),
    ]
