# Generated by Django 4.1.5 on 2023-01-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_administrator_profile_alter_developer_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='specialty',
            field=models.CharField(choices=[('Front', 'Frontend'), ('Back', 'Backend'), ('Full-Stack', 'Full-Stack'), ('DevOps', 'Development & Operations')], max_length=200),
        ),
    ]
