# Generated by Django 4.1.5 on 2023-01-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0008_alter_team_project_manager_alter_team_team_lead'),
        ('employee', '0004_rename_specialty_developer_specialties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='team',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='developer_team',
                                    to='project.team'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='team',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='project_manager_team',
                                    to='project.team'),
        ),
    ]
