# Generated by Django 4.1.5 on 2023-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_developer_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='skill_level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Junior Plus', 'Junior Plus'), ('Middle', 'Middle'), ('Middle Plus', 'Middle Plus'), ('Senior', 'Senior')], default='Junior', max_length=200),
        ),
        migrations.AlterField(
            model_name='developer',
            name='specialty',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full-Stack', 'Full-Stack'), ('Development & Operations', 'Development & Operations')], max_length=200),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='technology_category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Development & Operations', 'Development & Operations'), ('General technologies', 'General technologies')], max_length=200),
        ),
    ]
