# Generated by Django 4.1.5 on 2023-01-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_developer_skill_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperOrganizationSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full-Stack', 'Full-Stack'), ('Development & Operations', 'Development & Operations')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='developer',
            name='specialty',
        ),
    ]
