# Generated by Django 4.1.5 on 2023-01-08 20:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('team_name', models.CharField(max_length=200, unique=True)),
                ('developers', models.ManyToManyField(blank=True, related_name='developers', to='employee.developer')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='employee.projectmanager')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='employee.developer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('teams', models.ManyToManyField(related_name='teams', to='project.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
