# Generated by Django 4.1.5 on 2023-01-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0003_alter_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams',
                                         to='project.team'),
        ),
    ]
