# Generated by Django 4.1.5 on 2023-01-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0005_alter_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(auto_now_add=True),
        ),
    ]
