# Generated by Django 4.1.5 on 2023-01-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0004_rename_specialty_developer_specialties_and_more'),
        ('project', '0007_alter_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='project_manager',
                                    to='employee.projectmanager'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='team_lead',
                                    to='employee.developer'),
        ),
    ]
