# Generated by Django 4.1.5 on 2023-01-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0007_alter_developer_team'),
        ('project', '0009_alter_team_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='developers',
                                         to='employee.developer'),
        ),
    ]
