# Generated by Django 4.1.5 on 2023-01-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0005_alter_organization_owner'),
        ('project', '0010_alter_project_deadline_alter_team_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='organization.organization'),
        ),
    ]
