# Generated by Django 4.1.5 on 2023-01-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_avatar',
            field=models.ImageField(blank=True, null=True,
                                    upload_to='organization_avatar'),
        ),
    ]
