from .administrator import BaseConfigurationAdministratorsViewGeneric
from .technologies import BaseConfigurationTechnologiesViewGeneric
from .developer import BaseConfigurationDevelopersViewGeneric
from .project_manager import BaseConfigurationProjectManagersViewGeneric
