# Generated by Django 4.1.5 on 2023-01-08 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('teams', models.ManyToManyField(related_name='teams', to='project.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
