# Generated by Django 4.1.5 on 2023-01-08 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_team_create_at_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2023, 1, 8, 11, 4, 9, 550026, tzinfo=datetime.timezone.utc)),
        ),
    ]
