# Generated by Django 4.1.5 on 2023-01-08 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2023, 1, 8, 11, 28, 15, 95122, tzinfo=datetime.timezone.utc)),
        ),
    ]
