# Generated by Django 4.1.5 on 2023-01-10 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0004_alter_project_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=datetime.date(2023, 1, 10)),
        ),
    ]
