# Generated by Django 4.1.5 on 2023-01-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_specialty_developerorganizationspecialty_specialties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='specialty',
            new_name='specialties',
        ),
        migrations.RenameField(
            model_name='developerorganizationspecialty',
            old_name='specialties',
            new_name='specialty',
        ),
    ]
