# Generated by Django 4.1.5 on 2023-01-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='profile_avatar',
        ),
        migrations.AlterField(
            model_name='permissions',
            name='role_name',
            field=models.CharField(choices=[('Administrator', 'Administrator'),
                                            ('Product manager',
                                             'Product manager'),
                                            ('Developer', 'Developer')],
                                   max_length=200, unique=True),
        ),
    ]
