# Generated by Django 4.1.5 on 2023-01-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_user',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
