# Generated by Django 4.1.5 on 2023-01-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
