# Generated by Django 4.1.5 on 2023-01-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='update_at',
        ),
    ]
